In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
dataset=pd.read_csv('/content/drive/My Drive/Machine Learning lab/Social_Network_Ads.csv')
print(dataset)
dataset.isnull().sum()

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]


User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
x=dataset.iloc[:,[2,3]].values
y=dataset.iloc[:,4].values
print(x)
print(y)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder_x=LabelEncoder()
x[:,0]=label_encoder_x.fit_transform(x[:,0])
print(x)

[[     1  19000]
 [    17  20000]
 [     8  43000]
 [     9  57000]
 [     1  76000]
 [     9  58000]
 [     9  84000]
 [    14 150000]
 [     7  33000]
 [    17  65000]
 [     8  80000]
 [     8  52000]
 [     2  86000]
 [    14  18000]
 [     0  82000]
 [    11  80000]
 [    29  25000]
 [    27  26000]
 [    28  28000]
 [    30  29000]
 [    27  22000]
 [    29  49000]
 [    30  41000]
 [    27  22000]
 [    28  23000]
 [    29  20000]
 [    31  28000]
 [    29  30000]
 [    11  43000]
 [    13  18000]
 [    13  74000]
 [     9 137000]
 [     3  16000]
 [    10  44000]
 [     9  90000]
 [    17  27000]
 [    15  28000]
 [    12  49000]
 [     8  72000]
 [     9  31000]
 [     9  17000]
 [    15  51000]
 [    17 108000]
 [    12  15000]
 [    10  84000]
 [     5  20000]
 [     7  79000]
 [     9  54000]
 [    12 135000]
 [    13  89000]
 [     6  32000]
 [     0  44000]
 [    11  83000]
 [    17  23000]
 [     9  58000]
 [     6  55000]
 [     5  48000]
 [    10  79000]
 [     4  1800

In [ ]:
 from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=5)
print(x_train,x_test,y_train,y_test)

[[    28  23000]
 [    10  44000]
 [    33  23000]
 [    21 106000]
 [    17  50000]
 [     8  86000]
 [     9  84000]
 [     8  80000]
 [    36 108000]
 [    10  59000]
 [    41  42000]
 [    21  42000]
 [    41  88000]
 [    29  51000]
 [    17  73000]
 [    11  75000]
 [    23  60000]
 [    17  60000]
 [    24 149000]
 [    38 133000]
 [    22  61000]
 [    31  28000]
 [    18  50000]
 [    35  82000]
 [    17  22000]
 [    30  33000]
 [    39  60000]
 [    17  88000]
 [     8  15000]
 [     5  20000]
 [    19  52000]
 [     7  79000]
 [    18 126000]
 [    30  35000]
 [    11  80000]
 [     4  18000]
 [    38  60000]
 [    30 141000]
 [    14 117000]
 [    36  70000]
 [     9  31000]
 [    20  50000]
 [    29  20000]
 [    34 150000]
 [    12  62000]
 [     7  87000]
 [     0  44000]
 [    28  82000]
 [     8  52000]
 [    27  26000]
 [     5  82000]
 [    26 139000]
 [    29  23000]
 [    17  25000]
 [     4  63000]
 [     8  35000]
 [     1  76000]
 [    20  55000]
 [    14  8600

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
print(x_train,x_test)

[[ 0.77063564 -1.37090753]
 [-0.95681661 -0.74731782]
 [ 1.25048349 -1.37090753]
 [ 0.09884866  1.09375655]
 [-0.28502962 -0.56914934]
 [-1.14875575  0.49986159]
 [-1.05278618  0.44047209]
 [-1.14875575  0.3216931 ]
 [ 1.5383922   1.15314605]
 [-0.95681661 -0.3018966 ]
 [ 2.01824005 -0.80670732]
 [ 0.09884866 -0.80670732]
 [ 2.01824005  0.55925109]
 [ 0.86660521 -0.53945459]
 [-0.28502962  0.11382987]
 [-0.86084704  0.17321936]
 [ 0.2907878  -0.27220186]
 [-0.28502962 -0.27220186]
 [ 0.38675737  2.37063071]
 [ 1.73033134  1.89551474]
 [ 0.19481823 -0.24250711]
 [ 1.05854435 -1.22243379]
 [-0.18906005 -0.56914934]
 [ 1.44242263  0.3810826 ]
 [-0.28502962 -1.40060228]
 [ 0.96257478 -1.07396005]
 [ 1.82630091 -0.27220186]
 [-0.28502962  0.55925109]
 [-1.14875575 -1.60846551]
 [-1.43666446 -1.45999177]
 [-0.09309048 -0.50975984]
 [-1.24472532  0.29199835]
 [-0.18906005  1.68765151]
 [ 0.96257478 -1.01457056]
 [-0.86084704  0.3216931 ]
 [-1.53263403 -1.51938127]
 [ 1.73033134 -0.27220186]
 

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion='entropy',random_state=42)
classifier.fit(x_train,y_train)
classifier.score(x_train,y_train)
y_pred=classifier.predict(x_test)
print(y_pred)


[1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0
 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 1 1 0 1 0 0 0 1 0 0 1 0 1 1 0 1
 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1]


In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[59  7]
 [11 23]]


In [ ]:
from sklearn.metrics import accuracy_score
print((accuracy_score(y_test,y_pred)*100))

82.0


In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
precision=precision_score(y_test,y_pred,average='binary')
print((precision)*100) 

76.66666666666667


In [ ]:
recall=recall_score(y_test,y_pred,average='binary')
print((recall)*100)

67.64705882352942


In [ ]:
f1=f1_score(y_test,y_pred,average='binary')
print((f1)*100)

71.875


In [ ]:
output=0
#Gender =  1#@param {type:"number"}
Age =  45#@param {type:"number"}
Estimated_Salary = 567894#@param {type:"number"}

In [ ]:
output= classifier.predict(sc.transform([[Age,Estimated_Salary]]))
print("Purchased", output)
if output==[1]:
  print("Item will be purchased")
else:
  print("item will not be purchased")

Purchased [1]
Item will be purchased


In [ ]:
import pickle 
print("[INFO] Saving model...")
# Save the trained model as a pickle string. 
saved_model=pickle.dump(classifier,open('/content/drive/My Drive/Machine Learning lab/Exp3.pkl', 'wb')) 
# Saving model to disk

[INFO] Saving model...


In [ ]:
# Load the pickled model 
model = pickle.load(open('/content/drive/My Drive/Machine Learning lab/Exp3.pkl','rb'))  
# Use the loaded pickled model to make predictions 
model.predict(x_test)

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1])

In [ ]:
!pip install streamlit

     |████████████████████████████████| 10.1 MB 5.6 MB/s 
     |████████████████████████████████| 111 kB 43.8 MB/s 
     |████████████████████████████████| 164 kB 44.7 MB/s 
     |████████████████████████████████| 181 kB 37.4 MB/s 
     |████████████████████████████████| 76 kB 4.1 MB/s 
     |████████████████████████████████| 4.3 MB 36.2 MB/s 
     |████████████████████████████████| 63 kB 1.8 MB/s 
     |████████████████████████████████| 130 kB 47.5 MB/s 
     |████████████████████████████████| 428 kB 48.7 MB/s 
     |████████████████████████████████| 130 kB 47.9 MB/s 
     |████████████████████████████████| 793 kB 41.1 MB/s 
     |████████████████████████████████| 381 kB 45.4 MB/s 
  Created wheel for blinker: filename=blinker-1.4-py3-none-any.whl size=13478 sha256=38c3c6d1c740c5e6c9cf33b84c644f82f9960b5f96b0729d062d0956840084cb
  Stored in directory: /root/.cache/pip/wheels/22/f5/18/df711b66eb25b21325c132757d4314db9ac5e8dabeaf196eab
Successfully built blinker
  Attempting uninstall: 

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Load the pickled model
import pickle
pickle_in = open("/content/drive/My Drive/Machine Learning lab/Exp3.pkl","rb")
model=pickle.load(pickle_in)
#model = pickle.load(open('/content/drive/My Drive/Machine Learning lab/Exp3.pkl','rb'))


In [ ]:
%%writefile app.py
import streamlit as st 
#from PIL import Image
import pickle
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
st.set_option('deprecation.showfileUploaderEncoding', False)
# Load the pickled model
pickle_in = open("/content/drive/My Drive/Machine Learning lab/Exp3.pkl","rb")
model=pickle.load(pickle_in)
dataset= pd.read_csv('/content/drive/My Drive/Machine Learning lab/Social_Network_Ads.csv')
x = dataset.iloc[:, [2, 3]].values
from sklearn.preprocessing import LabelEncoder
labelencoder_x = LabelEncoder()
x[:, 0] = labelencoder_x.fit_transform(x[:, 0])
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
def predict_note_authentication(UserID,Gender,Age,EstimatedSalary):
  output= model.predict(sc.transform([[Age,EstimatedSalary]]))
  print("Purchased", output)
  if output==[1]:
    prediction="Item will be purchased"
  else:
    prediction="Item will not be purchased"
  print(prediction)
  return prediction
def main():
    st.title("Item Purchase Prediction")
    html_temp = """
   <div class="" style="background-color:blue;" >
   <div class="clearfix">           
   <div class="col-md-12">
   <center><p style="font-size:40px;color:white;margin-top:10px;">Poornima Institute of Engineering & Technology</p></center> 
   <center><p style="font-size:30px;color:white;margin-top:10px;">Department of Computer Engineering</p></center> 
   </div>
   </div>
   </div>
   """
    st.markdown(html_temp,unsafe_allow_html=True)
    UserID = st.text_input("UserID","Type Here")
    Gender = st.text_input("Gender","Type Here")
    Age = st.text_input("Age","Type Here")
    EstimatedSalary = st.text_input("EstimatedSalary","Type Here")
    resul=""
    if st.button("Predict"):
      result=predict_note_authentication(UserID,Gender,Age,EstimatedSalary)
      st.success('Model has predicted {}'.format(result))
    if st.button("About"):
      st.text("Developed by Nikhil Rastogi")
      

if __name__=='__main__':
  main()

Overwriting app.py


In [ ]:
!nohup streamlit run  app.py &

nohup: appending output to 'nohup.out'


In [ ]:
!pip install pyngrok

     |████████████████████████████████| 745 kB 4.9 MB/s 
  Created wheel for pyngrok: filename=pyngrok-5.1.0-py3-none-any.whl size=19007 sha256=55b3754858376f565896c878e4afd44cf8c4080c875fb1972908b96d47e418f7
  Stored in directory: /root/.cache/pip/wheels/bf/e6/af/ccf6598ecefecd44104069371795cb9b3afbcd16987f6ccfb3
Successfully built pyngrok


In [ ]:
!ngrok authtoken 27SG7m07r7yNhUbaJStDzzpKtyT_5duexPykaNaiwkWfr7W2L

Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml


In [ ]:
from pyngrok import ngrok
url=ngrok.connect(port='8050')
url

<NgrokTunnel: "http://4e4a-34-132-72-107.ngrok.io" -> "http://localhost:80">

In [ ]:
!streamlit run --server.port 80 app.py

2022-04-09 06:05:19.486 INFO    numexpr.utils: NumExpr defaulting to 2 threads.

  You can now view your Streamlit app in your browser.

  Network URL: http://172.28.0.2:80
  External URL: http://34.132.72.107:80

  Stopping...
^C
